"""A small local server for the web interface in `web/`.

`indicrag ask` reloads the dense encoder on every call, which is most of its
~50 s per query. The server loads the system once and keeps it warm, so the
web Playground answers in about a quarter of a second (extractive) or a minute (with a
generator). Standard library only. Bound to localhost by default; `--host 0.0.0.0`
serves it publicly (the Hugging Face Space in deploy/ does), and then the
limits below are what stand between the page and anyone's scripts:

    INDICRAG_RATE_PER_MIN   questions per visitor per minute   (default 12)
    INDICRAG_RATE_PER_DAY   questions per visitor per day      (default 300)
    INDICRAG_API_DAILY_CAP  hosted-model calls per day, total  (default 1000)
    INDICRAG_TRUST_PROXY=1  read the visitor from X-Forwarded-For (behind a proxy)

Queries are never logged.

    indicrag serve                      # http://127.0.0.1:8000
    indicrag serve --gguf <model.gguf>  # generated rather than extracted answers
    indicrag serve --api groq           # generated by a hosted model (GROQ_API_KEY)
    indicrag serve --api gemini         # or Gemini (GEMINI_API_KEY)

Routes:

    GET  /                 web/index.html and its static files
    GET  /api/health       {"ok": true, "passages": 694, "generator": "..."}
    GET  /api/demo         the rehearsed outputs in docs/demo/, for the page's examples
    POST /api/ask          {"query": "...", "method": "hybrid", "bm25_floor": 18.08,
                            "generator": "extractive" | "<a loaded generator>"}
"""

from __future__ import annotations

import json
import mimetypes
import os
import threading
import time
from collections import deque
from dataclasses import dataclass, field
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

from .models import Passage

#: Retrieval methods the page may request; anything else is refused rather
#: than passed through to `retrieve()`.
METHODS = ("hybrid", "hybrid-rrf", "hybrid-weighted", "bm25", "tfidf", "dense")
#: The dev-fitted BM25 abstention floor (paper §VI-H).
DEFAULT_FLOOR = 18.08
MAX_QUERY_CHARS = 500
#: The only files outside web/ the page links to. An allowlist, not a directory.
PAPER_FILES = ("IndicRAG-QA.pdf", "IndicRAG-QA-IEEE.pdf", "IndicRAG-QA-slides.pptx")


@dataclass
class System:
    passages: list[Passage]
    retrievers: Any
    provider: Any = None
    notes: list[str] = field(default_factory=list)
    #: Every generator loaded, by name. "extractive" (None) is always there, so
    #: a request can compare the model's answer with the extracted sentence.
    providers: dict[str, Any] = field(default_factory=lambda: {"extractive": None})

    @property
    def default_generator(self) -> str:
        return getattr(self.provider, "name", None) or "extractive"


def load_system(
    passages: list[Passage], *, gguf: str = "", api: str = "", model: str = "", say=None
) -> System:
    """Load the lexical index, the primary dense encoder and, optionally, generators.

    Shared by `ask` and `serve`, so both run the same system. A missing dense
    index is reported, not fatal: `hybrid` then degrades to lexical retrieval,
    and the caller is told so rather than left to notice the scores.
    """
    from .config import get_settings
    from .index.lexical import LexicalIndex
    from .pipeline import Retrievers

    say = say or (lambda _m: None)
    cfg = get_settings()
    retrievers = Retrievers(lexical=LexicalIndex.load(cfg.lex_dir))
    notes: list[str] = []
    try:
        from .index.dense import DenseIndex, Encoder
        from .index.encoders import get

        spec = get(cfg.encoder_primary)
        retrievers.dense = DenseIndex.load(spec, cfg.emb_dir, passages)
        retrievers.encoder = Encoder(spec)
    except Exception as exc:  # noqa: BLE001 -- reported, not swallowed
        note = f"dense index unavailable ({type(exc).__name__}: {exc}); hybrid falls back to lexical"
        notes.append(note)
        say(f"# {note}")

    providers: dict[str, Any] = {"extractive": None}
    if gguf:
        from .rag.providers import LlamaCppProvider

        local = LlamaCppProvider(gguf, n_ctx=cfg.llm_n_ctx, n_threads=cfg.llm_n_threads)
        local.name = "local:" + Path(gguf).stem
        providers[local.name] = local
    if api:
        from .rag.providers import OpenAICompatProvider

        hosted = OpenAICompatProvider.from_preset(api, model=model, max_tokens=cfg.llm_max_tokens)
        providers[hosted.name] = hosted
        say(f"# answers from {hosted.name}: questions and retrieved passages are sent to that API")
    # The hosted model, if any, answers by default; then the local one.
    default = next((p for n, p in reversed(providers.items()) if p is not None), None)
    return System(passages=passages, retrievers=retrievers, provider=default, notes=notes,
                  providers=providers)


def handle_ask(payload: Any, system: System) -> tuple[int, dict]:
    """Validate a request and answer it. Returns (HTTP status, JSON body)."""
    from .pipeline import answer_query

    if not isinstance(payload, dict):
        return 400, {"error": "expected a JSON object"}
    query = str(payload.get("query") or "").strip()
    if not query:
        return 400, {"error": "query is empty"}
    if len(query) > MAX_QUERY_CHARS:
        return 400, {"error": f"query is longer than {MAX_QUERY_CHARS} characters"}
    method = str(payload.get("method") or "hybrid")
    if method not in METHODS:
        return 400, {"error": f"method must be one of {', '.join(METHODS)}"}
    try:
        floor = float(payload.get("bm25_floor", DEFAULT_FLOOR))
        k = int(payload.get("k", 5))
    except (TypeError, ValueError):
        return 400, {"error": "bm25_floor and k must be numbers"}
    k = max(1, min(k, 10))
    generator = str(payload.get("generator") or system.default_generator)
    if generator not in system.providers:
        return 400, {"error": f"generator must be one of {', '.join(system.providers)}"}

    from .rag.providers import APIError

    try:
        result = answer_query(
            query, system.passages, retrievers=system.retrievers, method=method, k=k,
            bm25_floor=max(0.0, floor), provider=system.providers[generator],
        )
    except APIError as exc:
        # A hosted model being unreachable or rate-limited is the user's to see,
        # not a crash: the message names the provider and the status.
        return 502, {"error": str(exc)}
    return 200, result.as_dict()


class RateLimiter:
    """Sliding-window limits per visitor, and a daily cap on hosted-model calls.

    In memory, so a restart resets it -- fine for a demo Space, and it keeps
    the server dependency-free. The hosted-model cap is global because it is
    a budget: it protects the API key's quota, not any one visitor.
    """

    def __init__(self, per_min: int = 12, per_day: int = 300, api_daily_cap: int = 1000, clock=time.time):
        self.per_min, self.per_day, self.api_daily_cap = per_min, per_day, api_daily_cap
        self._clock = clock
        self._hits: dict[str, deque] = {}
        self._api: deque = deque()
        self._lock = threading.Lock()

    @classmethod
    def from_env(cls) -> RateLimiter:
        def num(name, default):
            try:
                return int(os.environ.get(name, default))
            except ValueError:
                return default
        return cls(num("INDICRAG_RATE_PER_MIN", 12), num("INDICRAG_RATE_PER_DAY", 300),
                   num("INDICRAG_API_DAILY_CAP", 1000))

    def check(self, visitor: str, *, hosted: bool) -> str | None:
        """Record one question. Returns why it is refused, or None if allowed."""
        now = self._clock()
        with self._lock:
            hits = self._hits.setdefault(visitor, deque())
            while hits and now - hits[0] > 86400:
                hits.popleft()
            last_min = sum(1 for t in hits if now - t < 60)
            if last_min >= self.per_min:
                return f"slow down: at most {self.per_min} questions a minute"
            if len(hits) >= self.per_day:
                return f"daily limit reached ({self.per_day} questions)"
            if hosted:
                while self._api and now - self._api[0] > 86400:
                    self._api.popleft()
                if len(self._api) >= self.api_daily_cap:
                    return "the hosted model's daily budget is used up; try the extracted answer"
                self._api.append(now)
            hits.append(now)
            if len(self._hits) > 10000:     # forget idle visitors so memory stays bounded
                for key in [k for k, v in self._hits.items() if not v or now - v[-1] > 86400]:
                    del self._hits[key]
        return None


def _demo_outputs(demo_dir: Path) -> list[dict]:
    out = []
    for path in sorted(demo_dir.glob("*.json")):
        try:
            out.append(json.loads(path.read_text(encoding="utf-8")))
        except (OSError, json.JSONDecodeError):
            continue
    return out


#: Sent with every response. The page's only third parties are Google Fonts.
#: Framing is governed by `frame-ancestors` alone: X-Frame-Options has no way to
#: allow huggingface.co, which shows a Space inside an iframe.
SECURITY_HEADERS = {
    "X-Content-Type-Options": "nosniff",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "Content-Security-Policy": (
        "default-src 'self'; script-src 'self' 'unsafe-inline'; "
        "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; "
        "font-src https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self'; "
        "frame-ancestors 'self' https://huggingface.co https://*.hf.space"
    ),
}


def make_handler(
    system: System, web_dir: Path, demo_dir: Path, paper_dir: Path | None = None,
    limiter: RateLimiter | None = None, trust_proxy: bool = False,
):
    web_root = web_dir.resolve()
    limiter = limiter or RateLimiter()
    # Retrieval shares one encoder and one index; answering is serialised so
    # concurrent visitors cannot interleave inside them. Static files and
    # health checks are served in parallel.
    answer_lock = threading.Lock()

    class Handler(BaseHTTPRequestHandler):
        server_version = "indicrag"

        def _send(self, status: int, body: bytes, ctype: str, cache: bool = False) -> None:
            self.send_response(status)
            self.send_header("Content-Type", ctype)
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "public, max-age=300" if cache else "no-store")
            for k, v in SECURITY_HEADERS.items():
                self.send_header(k, v)
            self.end_headers()
            self.wfile.write(body)

        def _visitor(self) -> str:
            if trust_proxy:
                fwd = self.headers.get("X-Forwarded-For", "")
                if fwd:
                    return fwd.split(",")[0].strip()
            return self.client_address[0]

        def _json(self, status: int, obj: Any) -> None:
            self._send(status, json.dumps(obj, ensure_ascii=False).encode("utf-8"),
                       "application/json; charset=utf-8")

        def do_GET(self) -> None:  # noqa: N802 -- http.server's naming
            path = self.path.split("?", 1)[0]
            if path == "/api/health":
                self._json(200, {"ok": True, "passages": len(system.passages),
                                 "generator": system.default_generator,
                                 "generators": list(system.providers), "notes": system.notes})
                return
            if path == "/api/demo":
                self._json(200, _demo_outputs(demo_dir))
                return
            if paper_dir is not None and path.startswith("/paper/"):
                name = path[len("/paper/"):]
                target = paper_dir / name
                if name in PAPER_FILES and target.is_file():
                    ctype = mimetypes.guess_type(name)[0] or "application/octet-stream"
                    self._send(200, target.read_bytes(), ctype, cache=True)
                else:
                    self._send(404, b"not found", "text/plain; charset=utf-8")
                return
            rel = "index.html" if path in ("", "/") else path.lstrip("/")
            target = (web_root / rel).resolve()
            # Serve files under web/ only; a path that resolves outside it is a 404.
            inside = web_root in target.parents
            if not inside or not target.is_file():
                self._send(404, b"not found", "text/plain; charset=utf-8")
                return
            ctype = mimetypes.guess_type(target.name)[0] or "application/octet-stream"
            if ctype.startswith("text/") or ctype.endswith("javascript"):
                ctype += "; charset=utf-8"
            self._send(200, target.read_bytes(), ctype, cache=not target.name.endswith(".html"))

        def do_POST(self) -> None:  # noqa: N802
            if self.path.split("?", 1)[0] != "/api/ask":
                self._json(404, {"error": "not found"})
                return
            length = int(self.headers.get("Content-Length") or 0)
            if length > 10_000:
                self._json(413, {"error": "request too large"})
                return
            try:
                payload = json.loads(self.rfile.read(length) or b"{}")
            except json.JSONDecodeError:
                self._json(400, {"error": "body is not JSON"})
                return
            generator = str((payload or {}).get("generator") or system.default_generator) \
                if isinstance(payload, dict) else system.default_generator
            refused = limiter.check(self._visitor(), hosted=generator not in ("extractive", "")
                                    and not generator.startswith("local:"))
            if refused:
                self._json(429, {"error": refused})
                return
            with answer_lock:
                status, body = handle_ask(payload, system)
            self._json(status, body)

        def log_message(self, fmt: str, *args) -> None:
            # Method, path and status only: never the query, which may be personal.
            print(f"  {self.command} {self.path.split('?', 1)[0]}  {args[1] if len(args) > 1 else ''}",
                  flush=True)

    return Handler


def serve(
    system: System, *, host: str, port: int, web_dir: Path, demo_dir: Path, paper_dir: Path
) -> None:
    trust = os.environ.get("INDICRAG_TRUST_PROXY", "") == "1"
    handler = make_handler(system, web_dir, demo_dir, paper_dir, RateLimiter.from_env(), trust)
    httpd = ThreadingHTTPServer((host, port), handler)
    httpd.daemon_threads = True
    print(f"IndicRAG-QA web interface on http://{host}:{port}  (Ctrl+C to stop)")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        httpd.server_close()
