"""Assemble the section drafts into one ordered paper.

The sections are written in separate files because they were drafted at
different times against different dependencies -- III-V needed nothing pending,
II needed the literature pass, VI needs the gold set. That is a good way to
write and a bad way to submit: five files, each with its own working preamble,
and a `draft.md` still holding a superseded copy of the abstract.

So `paper.md` is built, never edited. One command, one source of truth per
section, and the working preambles (the `[PROBE]` reminders, the notes on what
each file was waiting for) are stripped on the way through rather than deleted
from the drafts, where they are still useful.

A section whose source is missing becomes a visible placeholder rather than a
silent gap, for the same reason `eval all` degrades instead of failing: the
paper is assembled repeatedly while sections are still landing, and a build that
quietly omits Section VI would eventually produce a submission without it.

    python scripts/build-paper.py

Writes paper/paper.md. Run it after editing any section draft.
"""

from __future__ import annotations

import datetime
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAPER = ROOT / "paper"

#: Headings that name the draft's working structure rather than the paper's.
#: `## Draft text` is what Section II is called in the file that also holds the
#: framing-gate analysis and the bibliography checklist; the paper wants the
#: section title.
RENAME = {"## Draft text": "## II. Related Work", "## Bibliography": "## References"}

#: (source file, first heading to keep, heading to stop before or None).
#: Order is the paper's order, not the drafting order.
SECTIONS: list[tuple[str, str, str | None]] = [
    ("sections-I-abstract.md", "## Abstract", None),
    ("section-II-related-work.md", "## Draft text", "## Bibliography"),
    ("sections-III-IV-V.md", "## III. Dataset", None),
    ("sections-VI-results.md", "## VI. Results", None),
    ("sections-VII-X.md", "## VII. Error Analysis", None),
]

REFERENCES = ("section-II-related-work.md", "## Bibliography", None)

PLACEHOLDER = """## VI. Results

> **NOT YET WRITTEN.** This section waits on the Module 4 and Module 5 runs and
> on human verification of the gold set. The retrieval tables it will carry are
> measured and committed under `evals/`; the question-answering and
> answerability tables are not yet complete.
>
> Assembled papers containing this block are drafts and must not be submitted.
"""


def extract(path: Path, start: str, stop: str | None) -> str | None:
    """Pull one section out of a draft file, dropping its working preamble."""
    if not path.exists():
        return None
    lines = path.read_text(encoding="utf-8").splitlines()

    try:
        first = next(i for i, ln in enumerate(lines) if ln.startswith(start))
    except StopIteration:
        return None

    last = len(lines)
    if stop is not None:
        for i in range(first + 1, len(lines)):
            if lines[i].startswith(stop):
                last = i
                break

    body = "\n".join(lines[first:last]).strip()
    for old, new in RENAME.items():
        if body.startswith(old):
            body = new + body[len(old) :]
            break
    # Drop a trailing rule left over from the draft's own section divider.
    return re.sub(r"\n-{3,}\s*$", "", body).strip()


def build() -> tuple[str, list[str]]:
    stamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    out = [
        "# Script-Aware Fusion for Cross-Lingual Retrieval",
        "",
        "**Why naive hybrid retrieval fails on Indic and code-mixed queries**",
        "",
        "IndicRAG-QA · CSET 346, Bennett University",
        "",
        f"*Assembled {stamp} by `scripts/build-paper.py`. Do not edit this file; "
        "edit the section drafts and rebuild.*",
        "",
        "*Retrieval figures marked `[PROBE]` are measured on 180 synthetic probes, "
        "not on the human-verified gold set.*",
        "",
        "---",
        "",
    ]

    missing: list[str] = []
    for name, start, stop in SECTIONS:
        body = extract(PAPER / name, start, stop)
        if body is None:
            missing.append(start.lstrip("# "))
            body = PLACEHOLDER.strip() if start.startswith("## VI.") else (
                f"## {start.lstrip('# ')}\n\n> **MISSING**: no source found in `{name}`."
            )
        out += [body, "", "---", ""]

    refs = extract(PAPER / REFERENCES[0], REFERENCES[1], REFERENCES[2])
    if refs:
        out += [refs, ""]
    else:
        missing.append("References")

    return "\n".join(out), missing


def main() -> int:
    text, missing = build()
    target = PAPER / "paper.md"
    target.write_text(text, encoding="utf-8", newline="\n")

    words = len(re.sub(r"[#>|*`-]", " ", text).split())
    print(f"wrote {target.relative_to(ROOT)}  ({words} words)")
    for name in missing:
        print(f"  MISSING: {name}")
    if missing:
        print("\nThis is a draft. Sections above are placeholders, not omissions.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
