"""Embed the rehearsed demo outputs into the web page's offline fallback.

The Playground in web/index.html answers live through `indicrag serve`. Opened
as a plain file, it has no server to ask, so it shows the six outputs that
scripts/run-demo.py recorded under docs/demo/. This writes them to
web/demo-data.js, which the page loads with a plain <script> tag -- a fetch()
of a local JSON file is blocked under file://.

    python scripts/build-web.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEMO = ROOT / "docs" / "demo"
OUT = ROOT / "web" / "demo-data.js"


def main() -> int:
    outputs = [json.loads(p.read_text(encoding="utf-8")) for p in sorted(DEMO.glob("*.json"))]
    if not outputs:
        print(f"no demo outputs in {DEMO}; run scripts/run-demo.py first")
        return 1
    body = json.dumps(outputs, ensure_ascii=False, indent=1)
    OUT.write_text(
        "// Generated by scripts/build-web.py from docs/demo/*.json. Do not edit.\n"
        f"window.INDICRAG_DEMO = {body};\n",
        encoding="utf-8", newline="\n",
    )
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(outputs)} outputs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
