// Generated by scripts/build-web.py. Do not edit by hand.
window.INDICRAG = {
 "demo": [
  {
   "query": "How much is the annual premium of Pradhan Mantri Suraksha Bima Yojana?",
   "query_type": "English",
   "answerability": "ANSWERABLE",
   "answer": "Pradhan Mantri Suraksha Bima Yojana is available to people (Indian Resident or NRI) between 18 and 70 years of age with bank accounts.",
   "confidence": 0.95,
   "query_lang": "en",
   "answer_lang": "en",
   "citations": [
    {
     "passage_id": "suraksha-bima-en#p0001",
     "doc_id": "suraksha-bima-en",
     "scheme": "suraksha-bima",
     "lang": "en",
     "section_path": "Provisions",
     "score": 0.0328,
     "snippet": "Pradhan Mantri Suraksha Bima Yojana is available to people (Indian Resident or NRI) between 18 and 70 years of age with bank accounts. It has an annual premium of ₹20 (21¢ US). Goods and Services Tax (GST) is exempted on Pradhan Mantri Suraksha Bima Yojana. The amount is automatically debited from t"
    },
    {
     "passage_id": "jeevan-jyoti-en#p0000",
     "doc_id": "jeevan-jyoti-en",
     "scheme": "jeevan-jyoti",
     "lang": "en",
     "section_path": "Introduction",
     "score": 0.0318,
     "snippet": "Pradhan Mantri Jeevan Jyoti Bima Yojana (Prime Minister Jeevan Jyoti Insurance Scheme) is a Government-backed life insurance scheme in India. It was originally mentioned in the year 2015 budget speech by the then-Finance Minister, Arun Jaitley in February 2015. It was formally launched by Prime Mini"
    },
    {
     "passage_id": "suraksha-bima-en#p0003",
     "doc_id": "suraksha-bima-en",
     "scheme": "suraksha-bima",
     "lang": "en",
     "section_path": "Criticism",
     "score": 0.0318,
     "snippet": "The success rate of the Pradhan Mantri Suraksha Bima Yojana (PMSBY) can be viewed through its high enrollment figures (over 50 crore cumulative enrollments as of May 2025), extensive reach into rural areas, and low rejection rate; however, it has experienced challenges in timely claim settlement, wi"
    },
    {
     "passage_id": "suraksha-bima-en#p0000",
     "doc_id": "suraksha-bima-en",
     "scheme": "suraksha-bima",
     "lang": "en",
     "section_path": "Introduction",
     "score": 0.0317,
     "snippet": "Pradhan Mantri Suraksha Bima Yojana (PMSBY, translation: Prime Minister's Safety Insurance Scheme) is a government-backed accident insurance scheme in India. It was originally mentioned in the 2015 budget speech by Finance Minister Arun Jaitley in February 2015. It was formally launched by the Prime"
    },
    {
     "passage_id": "jeevan-jyoti-en#p0001",
     "doc_id": "jeevan-jyoti-en",
     "scheme": "jeevan-jyoti",
     "lang": "en",
     "section_path": "Introduction",
     "score": 0.0305,
     "snippet": "Those who register for auto debit facility will have auto renewal up to 55 years. However, a person over age 50 cannot register to this scheme. There is no need for a person to submit health report or certificate while joining to this scheme. In case of death due to any cause, the payment to the nom"
    }
   ],
   "explanation": "Extracted verbatim from suraksha-bima-en#p0001 (suraksha-bima, Provisions).",
   "retrieval": {
    "method": "hybrid",
    "k": 5,
    "top_score": 0.0328,
    "margin": 0.001,
    "n_candidates": 5,
    "bm25_top": 30.5053,
    "bm25_floor": 18.08
   },
   "model": "extractive",
   "prompt_hash": ""
  },
  {
   "query": "मनरेगा के तहत कितने दिन का रोजगार मिलता है?",
   "query_type": "Indic",
   "answerability": "ANSWERABLE",
   "answer": "2008-09 के दौरान 4,49,40,870 ग्रामीण परिवारों को मनरेगा के तहत रोजगार उपलब्ध कराया गया, जहां प्रत्येक परिवार में 48 कार्य दिवस का राष्ट्रीय औसत था।",
   "confidence": 0.7445,
   "query_lang": "hi",
   "answer_lang": "hi",
   "citations": [
    {
     "passage_id": "mgnrega-hi#p0004",
     "doc_id": "mgnrega-hi",
     "scheme": "mgnrega",
     "lang": "hi",
     "section_path": "क्रियान्वयन",
     "score": 0.0325,
     "snippet": "भारत का नियंत्रक एवं महालेखा परीक्षक (सीएजी) ने मनरेगा के कार्यान्वयन के प्रदर्शन लेखापरीक्षा में इस अधिनियम के कार्यान्वयन में \"बड़ी कमियों\" को पाया है। इस योजना को फरवरी 2006 में 200 जिलों में शुरू किया गया था और अंत में 593 जिलों तक विस्तारित किया गया। 2008-09 के दौरान 4,49,40,870 ग्रामीण परिवारो"
    },
    {
     "passage_id": "mgnrega-hi#p0002",
     "doc_id": "mgnrega-hi",
     "scheme": "mgnrega",
     "lang": "hi",
     "section_path": "योजना",
     "score": 0.0323,
     "snippet": "यह अधिनियम, राज्य सरकारों को \"मनरेगा योजनाओं\" को लागू करने के निर्देश देता है। मनरेगा के तहत, केन्द्र सरकार मजदूरी की लागत, माल की लागत का 3/4 और प्रशासनिक लागत का कुछ प्रतिशत वहन करती है। राज्य सरकारें बेरोजगारी भत्ता, माल की लागत का 1/4 और राज्य परिषद की प्रशासनिक लागत को वहन करती है। चूंकि राज्य "
    },
    {
     "passage_id": "mgnrega-hi#p0000",
     "doc_id": "mgnrega-hi",
     "scheme": "mgnrega",
     "lang": "hi",
     "section_path": "Introduction",
     "score": 0.032,
     "snippet": "महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी अधिनियम (मनरेगा / MNREGA) भारत में लागू एक रोजगार गारंटी योजना है, जिसे 5 सितम्बर 2005 को विधान द्वारा अधिनियमित किया गया। यह योजना प्रत्येक वित्तीय वर्ष में किसी भी ग्रामीण परिवार के उन वयस्क सदस्यों को 100 दिन का रोजगार उपलब्ध कराती है जो प्रतिदिन 220 "
    },
    {
     "passage_id": "mgnrega-hi#p0005",
     "doc_id": "mgnrega-hi",
     "scheme": "mgnrega",
     "lang": "hi",
     "section_path": "कार्य/गतिविधियां",
     "score": 0.031,
     "snippet": "मनरेगा ग्रामीण विकास और रोजगार के दोहरे लक्ष्य को प्राप्त करता है। मनरेगा यह उल्लेख करता है कि कार्य को ग्रामीण विकास गतिविधियों के एक विशिष्ट सेट की ओर उन्मुख होना चाहिए जैसे: जल संरक्षण और संचयन, वनीकरण, ग्रामीण संपर्क-तंत्र, बाढ़ नियंत्रण और सुरक्षा जिसमें शामिल है तटबंधों का निर्माण और मरम्मत, आ"
    },
    {
     "passage_id": "mgnrega-en#p0001",
     "doc_id": "mgnrega-en",
     "scheme": "mgnrega",
     "lang": "en",
     "section_path": "Introduction",
     "score": 0.0303,
     "snippet": "It aimed to enhance livelihood security in rural areas by providing at least 100 days of assured and guaranteed wage employment in a financial year to at least one member of every Indian rural household whose adult members volunteer to do unskilled manual work. Women are guaranteed one half of the j"
    }
   ],
   "explanation": "Extracted verbatim from mgnrega-hi#p0004 (mgnrega, क्रियान्वयन).",
   "retrieval": {
    "method": "hybrid",
    "k": 5,
    "top_score": 0.0325,
    "margin": 0.0003,
    "n_candidates": 5,
    "bm25_top": 19.3204,
    "bm25_floor": 18.08
   },
   "model": "extractive",
   "prompt_hash": ""
  },
  {
   "query": "Scholarship ke liye minimum eligibility kya hai?",
   "query_type": "Code-Mixed",
   "answerability": "UNANSWERABLE",
   "answer": "Insufficient information available in the provided documents.",
   "confidence": 0.9677,
   "query_lang": "hi-en",
   "answer_lang": "",
   "citations": [
    {
     "passage_id": "awas-yojana-hi#p0003",
     "doc_id": "awas-yojana-hi",
     "scheme": "awas-yojana",
     "lang": "hi",
     "section_path": "योजना > पात्रता",
     "score": 0.0323,
     "snippet": "इस योजना हेतु भारत सरकार द्वारा निम्न पात्रता मापदंड तय किया गया है:-\n\nआवेदक की उम्र 70 से कम हो, आवेदक या उसके परिवार के किसी सदस्य के नाम से कोई घर या फ्लॅट न हो, आवेदक द्वारा घर खरीदने के लिए किसी भी प्रकार का सरकारी छुट न लिया हो, घर का मालिकाना हक या तो महिला के नाम से हो, या उस परिवार में केवल"
    },
    {
     "passage_id": "sukanya-en#p0003",
     "doc_id": "sukanya-en",
     "scheme": "sukanya",
     "lang": "en",
     "section_path": "Summary",
     "score": 0.0313,
     "snippet": "If the girl is over 18 and married, normal closure is allowed. The Sukanya Samriddhi Yojana (SSY) scheme is highly flexible regarding annual deposit amounts. You are not required to deposit the same amount every year.Key Deposit RulesFlexible Amounts: You can choose to deposit any amount between the"
    },
    {
     "passage_id": "atal-pension-en#p0002",
     "doc_id": "atal-pension-en",
     "scheme": "atal-pension",
     "lang": "en",
     "section_path": "Scheme",
     "score": 0.0307,
     "snippet": "To be eligible to avail the scheme, a person's age should be between 18 and 40 years. The pension of the person joining the scheme depends on the investment made in it and the time limit of investment. In order to incentivize people to enroll in this scheme and widen its reach, the government announ"
    },
    {
     "passage_id": "sukanya-en#p0001",
     "doc_id": "sukanya-en",
     "scheme": "sukanya",
     "lang": "en",
     "section_path": "Summary",
     "score": 0.0288,
     "snippet": "The scheme was launched by Prime Minister Narendra Modi on 22 January 2015 in Panipat, Haryana. The accounts can be opened at any India Post office or a branch of some authorized commercial banks. Initially, the interest rate was set at 9.1% but later revised to 9.2% in late March 2015 for FY2015-16"
    },
    {
     "passage_id": "epfo-en#p0014",
     "doc_id": "epfo-en",
     "scheme": "epfo",
     "lang": "en",
     "section_path": "EPF calculation > Percentage breakdown",
     "score": 0.0281,
     "snippet": "EPFOF dues has two contributions. One is the employee's contribution which is deducted from employee's salary / wages and another is employer's contribution which is to be paid by the employer every month. The employee's contribution is 12% of the basic wage as per sec.2(b) of the act and employer's"
    }
   ],
   "explanation": "",
   "retrieval": {
    "method": "hybrid",
    "k": 5,
    "top_score": 0.0323,
    "margin": 0.001,
    "n_candidates": 5,
    "bm25_top": 10.2878,
    "bm25_floor": 18.08
   },
   "model": "",
   "prompt_hash": ""
  },
  {
   "query": "सुकन्या समृद्धि खाता कितने वर्ष में परिपक्व होता है?",
   "query_type": "Indic",
   "answerability": "ANSWERABLE",
   "answer": "सुकन्या समृद्धि में केवल जन्म से लेकर 10 वर्ष की उम्र की लड़की के नाम पर ही खाता खुलवाया जा सकता है | अर्थात सुकन्या समृद्धि के अंतर्गत 10 वर्ष से अधिक उम्र की लड़कियों का अकाउंट ओपन नहीं किया जा सकता है | इस योजना का लाभ हिंदू अविभाजित परिवार (HUF) एवं अनिवासी भारतीय (एन आर आई) नहीं प्राप्त कर सकते हैं | यदि खाता ओपन करने के पश्चात कोई बच्ची एन आर आई बन जाती है | तो उसे सुकन्या समृद्धि योजना का खाता बंद करना होगा | यदि खाता बंद नहीं किया जाता है | तो एन आर आई बनने के पश्चात इस खाते में किसी प्रकार का ब्याज प्रदान नहीं किया जाएगा |",
   "confidence": 0.6898,
   "query_lang": "hi",
   "answer_lang": "hi",
   "citations": [
    {
     "passage_id": "sukanya-hi#p0008",
     "doc_id": "sukanya-hi",
     "scheme": "sukanya",
     "lang": "hi",
     "section_path": "सुकन्‍या समृद्धि योजना में कौन खाता खोल सकता है –",
     "score": 0.0325,
     "snippet": "सुकन्या समृद्धि में केवल जन्म से लेकर 10 वर्ष की उम्र की लड़की के नाम पर ही खाता खुलवाया जा सकता है | अर्थात सुकन्या समृद्धि के अंतर्गत 10 वर्ष से अधिक उम्र की लड़कियों का अकाउंट ओपन नहीं किया जा सकता है | इस योजना का लाभ हिंदू अविभाजित परिवार (HUF) एवं अनिवासी भारतीय (एन आर आई) नहीं प्राप्त कर सकते"
    },
    {
     "passage_id": "sukanya-hi#p0000",
     "doc_id": "sukanya-hi",
     "scheme": "sukanya",
     "lang": "hi",
     "section_path": "Introduction",
     "score": 0.0323,
     "snippet": "सुकन्या समृद्धि भारत की एक छोटी बचत योजना है, जिसकी शुरुआत 'बेटी बचाओ बेटी पढ़ाओ' अभियान के तहत की गयी | जिसके अंतर्गत माता-पिता या कानूनी अभिभावक कन्या के नाम से खाता खोल सकते हैं इस योजना के अंतर्गत खाता खुलवाने के लिए बच्ची की आयु सीमा 10 वर्ष से कम होनी चाहिए । यह खाता किसी भी डाकखाने और निर्धार"
    },
    {
     "passage_id": "sukanya-hi#p0005",
     "doc_id": "sukanya-hi",
     "scheme": "sukanya",
     "lang": "hi",
     "section_path": "विशेषताएँ",
     "score": 0.032,
     "snippet": "इस स्थिति में खाते को प्रति वर्ष 50 रुपये पेनाल्टी के साथ दोबारा चालू किया जा सकता है, लेकिन न्यूनतम रकम भी जमा करनी होगी। 21 वर्ष की परिपक्वता अवधि पूरी होने के पहले खाताधारी लड़की रकम निकाल सकती है बशर्ते कि उसकी आयु 18 वर्ष की हो गई हो। इस स्थिति में वह कुल जमा राशि का 50 प्रतिशत ही निकाल पाएगी। "
    },
    {
     "passage_id": "sukanya-hi#p0004",
     "doc_id": "sukanya-hi",
     "scheme": "sukanya",
     "lang": "hi",
     "section_path": "विशेषताएँ",
     "score": 0.0312,
     "snippet": "खाते की वैधानिकता उसके खोले जाने की तारीख से लेकर 21 वर्ष की है, जिसके बाद रकम परिपक्व होकर उस लड़की को दे दी जाएगी जिसके नाम पर खाता है। यदि परिपक्वता के बाद खाता बंद नहीं किया जाता है तो बैलेंस रकम पर ब्याज मिलता रहेगा, जिसके बारे में समय-समय पर सूचना प्रदान की जाती रहेगी। यदि लड़की का विवाह 21 वर"
    },
    {
     "passage_id": "sukanya-hi#p0007",
     "doc_id": "sukanya-hi",
     "scheme": "sukanya",
     "lang": "hi",
     "section_path": "तुलना",
     "score": 0.0308,
     "snippet": "सार्वजनिक भविष्य निधि (PPF) और सुकन्या समृद्धि योजना (SSY) दोनों भारत सरकार द्वारा समर्थित दीर्घकालिक बचत योजनाएँ हैं। PPF में कोई भी पात्र भारतीय निवेश कर सकता है, जबकि SSY केवल बालिका के नाम पर खोले जाने वाले खाते के लिए उपलब्ध है। SSY में ब्याज दर सामान्यतः PPF की तुलना में अधिक रही है, जबकि दोनो"
    }
   ],
   "explanation": "Extracted verbatim from sukanya-hi#p0008 (sukanya, सुकन्‍या समृद्धि योजना में कौन खाता खोल सकता है –).",
   "retrieval": {
    "method": "hybrid",
    "k": 5,
    "top_score": 0.0325,
    "margin": 0.0003,
    "n_candidates": 5,
    "bm25_top": 26.4754,
    "bm25_floor": 18.08
   },
   "model": "extractive",
   "prompt_hash": ""
  },
  {
   "query": "What is the interest rate on a Kisan Credit Card loan in Nagaland?",
   "query_type": "English",
   "answerability": "ANSWERABLE",
   "answer": "The Kisan Credit Card (KCC) scheme is a credit scheme introduced in August 1998 by Indian public sector banks to issue kisan credit card to the farmers of India.",
   "confidence": 0.6548,
   "query_lang": "en",
   "answer_lang": "en",
   "citations": [
    {
     "passage_id": "kisan-credit-card-en#p0000",
     "doc_id": "kisan-credit-card-en",
     "scheme": "kisan-credit-card",
     "lang": "en",
     "section_path": "Introduction",
     "score": 0.0328,
     "snippet": "The Kisan Credit Card (KCC) scheme is a credit scheme introduced in August 1998 by Indian public sector banks to issue kisan credit card to the farmers of India. This model scheme was prepared by the National Bank for Agriculture and Rural Development (NABARD) on the recommendations of the R. V. Gup"
    },
    {
     "passage_id": "stand-up-india-hi#p0002",
     "doc_id": "stand-up-india-hi",
     "scheme": "stand-up-india",
     "lang": "hi",
     "section_path": "Stand Up India Scheme की मुख्य विशेषताए > स्टैंड उप इंडिया स्कीम का ऋण विवरण (Loan Details)",
     "score": 0.0581,
     "snippet": "ऋण राशि ₹10 लाख से ₹1 करोड़ तक ऋण का प्रकार - Composite Loan(Term Loan+Working capital) ब्याज दर - Marginal Cost of Lending Rate (MCLR) + अधिकतम 3% मार्जिन - अधिकतम 25% (योजना में 15% तक सहायता संभव) भुगतान अवधि - अधिकतम 7 वर्ष छूट अवधि - अधिकतम 18 महीने तक\n\nइस योजना के विषय में विस्तृत जानकारी नीचे"
    },
    {
     "passage_id": "indira-awaas-en#p0007",
     "doc_id": "indira-awaas-en",
     "scheme": "indira-awaas",
     "lang": "en",
     "section_path": "Eligibility > Who is not eligible",
     "score": 0.0318,
     "snippet": "13 parameters set by the government of India exclude households or individuals from this program:\n\nHousehold having three or four wheeler and motorized boat;\nHousehold having mechanized three or four wheeler agriculture or allied equipment;\nKisan credit card holder having limit of 50,000 rupees;\nHou"
    },
    {
     "passage_id": "sukanya-en#p0001",
     "doc_id": "sukanya-en",
     "scheme": "sukanya",
     "lang": "en",
     "section_path": "Summary",
     "score": 0.0303,
     "snippet": "The scheme was launched by Prime Minister Narendra Modi on 22 January 2015 in Panipat, Haryana. The accounts can be opened at any India Post office or a branch of some authorized commercial banks. Initially, the interest rate was set at 9.1% but later revised to 9.2% in late March 2015 for FY2015-16"
    },
    {
     "passage_id": "kisan-credit-card-hi#p0000",
     "doc_id": "kisan-credit-card-hi",
     "scheme": "kisan-credit-card",
     "lang": "hi",
     "section_path": "Introduction",
     "score": 0.0303,
     "snippet": "किसान क्रेडिट कार्ड ( केसीसी ) योजना भारत के किसानों को किसान क्रेडिट कार्ड जारी करने के लिए भारतीय सार्वजनिक क्षेत्र के बैंकों द्वारा अगस्त 1998 में शुरू की गई एक क्रेडिट योजना है। यह मॉडल योजना कृषि आवश्यकताओं के लिए अग्रिम प्रदान करने के लिए आरवी गुप्ता समिति की सिफारिशों पर राष्ट्रीय कृषि और ग्र"
    }
   ],
   "explanation": "Extracted verbatim from kisan-credit-card-en#p0000 (kisan-credit-card, Introduction).",
   "retrieval": {
    "method": "hybrid",
    "k": 5,
    "top_score": 0.0581,
    "margin": 0.0253,
    "n_candidates": 5,
    "bm25_top": 20.7458,
    "bm25_floor": 18.08
   },
   "model": "extractive",
   "prompt_hash": ""
  },
  {
   "query": "PMJDY ke tahat kitne bank khate khole gaye?",
   "query_type": "Code-Mixed",
   "answerability": "UNANSWERABLE",
   "answer": "Insufficient information available in the provided documents.",
   "confidence": 0.9683,
   "query_lang": "hi-en",
   "answer_lang": "",
   "citations": [
    {
     "passage_id": "jan-dhan-hi#p0000",
     "doc_id": "jan-dhan-hi",
     "scheme": "jan-dhan",
     "lang": "hi",
     "section_path": "Introduction",
     "score": 0.0317,
     "snippet": "प्रधानमंत्री जन धन योजना (संक्षेप में - पीएमजेडीवाई) भारत में वित्तीय समावेशन पर राष्ट्रीय मिशन है और जिसका उद्देश्य देश भर में सभी परिवारों को बैंकिंग सुविधाएं मुहैया कराना और हर परिवार का बैंक खाता खोलना है। इस योजना की घोषणा 15 अगस्त 2014 को तथा इसका शुभारंभ 28 अगस्त 2014 को भारतीय प्रधानमंत्री श"
    },
    {
     "passage_id": "jan-dhan-en#p0003",
     "doc_id": "jan-dhan-en",
     "scheme": "jan-dhan",
     "lang": "en",
     "section_path": "Performance",
     "score": 0.0313,
     "snippet": "Uttar Pradesh and West Bengal have 29% of the total deposits under the scheme, whereas Kerala and Goa became the first states in the country to have at least one basic bank account in every household. The total number of account holders stood at 294.8 million, including 176.1 million account holders"
    },
    {
     "passage_id": "pmkvy-hi#p0000",
     "doc_id": "pmkvy-hi",
     "scheme": "pmkvy",
     "lang": "hi",
     "section_path": "Introduction",
     "score": 0.0312,
     "snippet": "प्रधानमंत्री कौशल विकास योजना (PMKVY)। इसे प्रधानमंत्री यूथ ट्रेनिंग प्रोग्राम के नाम से भी जाना जाता है। भारत सरकार ने इस योजना को जुलाई 2015 में शुरू किया गया था। इस योजना के तहत 2020 तक एक करोड़ युवाओं को प्रशिक्षण (ट्रेनिंग) देने की योजना बनाई गई थी। इस योजना का उद्देश्य ऐसे लोगों को रोजगार मुहै"
    },
    {
     "passage_id": "mudra-en#p0006",
     "doc_id": "mudra-en",
     "scheme": "mudra",
     "lang": "en",
     "section_path": "Economic policies > Social welfare",
     "score": 0.0308,
     "snippet": "Modi launched Pradhan Mantri Jan Dhan Yojana (PMJDY) in August 2014. The initiative aimed to create bank accounts and debit cards for 150 million families, and to allow them an overdraft of ₹5,000 (US$52) and accident insurance. After the launch, 125.4 million accounts were opened by January 2015. T"
    },
    {
     "passage_id": "jan-dhan-en#p0004",
     "doc_id": "jan-dhan-en",
     "scheme": "jan-dhan",
     "lang": "en",
     "section_path": "Performance",
     "score": 0.0303,
     "snippet": "As of January 27, 2021, a total number of 417.5 million accounts have been opened under the Pradhan Mantri Jan Dhan Yojana (PMJDY), out of which 359.6 million accounts are operative. According to the World Bank's Spring 2025 Poverty and Equity Brief, approximately 171 million people in India moved o"
    }
   ],
   "explanation": "",
   "retrieval": {
    "method": "hybrid",
    "k": 5,
    "top_score": 0.0317,
    "margin": 0.0005,
    "n_candidates": 5,
    "bm25_top": 10.7209,
    "bm25_floor": 18.08
   },
   "model": "",
   "prompt_hash": ""
  }
 ],
 "fusion": {
  "id": "qa-en-hi-027",
  "question": "In the World Bank's Doing Business 2009 report, how many Indian cities were surveyed?",
  "answer": "17",
  "query_script": "latin",
  "gold": [
   "make-in-india-hi#p0009"
  ],
  "lexical": [
   {
    "id": "make-in-india-en#p0003",
    "rank": 1
   },
   {
    "id": "mgnrega-en#p0002",
    "rank": 2
   },
   {
    "id": "swachh-bharat-en#p0019",
    "rank": 3
   },
   {
    "id": "midday-meal-en#p0017",
    "rank": 4
   },
   {
    "id": "swachh-bharat-en#p0020",
    "rank": 5
   },
   {
    "id": "mudra-en#p0042",
    "rank": 6
   },
   {
    "id": "garib-kalyan-anna-en#p0011",
    "rank": 7
   },
   {
    "id": "aadhaar-en#p0040",
    "rank": 8
   },
   {
    "id": "make-in-india-en#p0005",
    "rank": 9
   },
   {
    "id": "midday-meal-en#p0018",
    "rank": 10
   },
   {
    "id": "atmanirbhar-en#p0000",
    "rank": 11
   },
   {
    "id": "mudra-en#p0049",
    "rank": 12
   },
   {
    "id": "jan-dhan-en#p0005",
    "rank": 13
   },
   {
    "id": "jan-dhan-en#p0000",
    "rank": 14
   },
   {
    "id": "aadhaar-en#p0036",
    "rank": 15
   },
   {
    "id": "smart-cities-en#p0004",
    "rank": 16
   },
   {
    "id": "jan-dhan-en#p0004",
    "rank": 17
   },
   {
    "id": "awas-yojana-en#p0008",
    "rank": 18
   },
   {
    "id": "pm-kisan-en#p0001",
    "rank": 19
   },
   {
    "id": "kgbv-en#p0002",
    "rank": 20
   },
   {
    "id": "swachh-bharat-en#p0027",
    "rank": 21
   },
   {
    "id": "rte-act-en#p0006",
    "rank": 22
   },
   {
    "id": "pds-en#p0028",
    "rank": 23
   },
   {
    "id": "aadhaar-en#p0034",
    "rank": 24
   },
   {
    "id": "nsap-en#p0007",
    "rank": 25
   },
   {
    "id": "rte-act-en#p0003",
    "rank": 26
   },
   {
    "id": "aadhaar-en#p0044",
    "rank": 27
   },
   {
    "id": "jan-dhan-en#p0002",
    "rank": 28
   },
   {
    "id": "icds-en#p0003",
    "rank": 29
   },
   {
    "id": "smart-cities-en#p0001",
    "rank": 30
   },
   {
    "id": "swachh-bharat-en#p0022",
    "rank": 31
   },
   {
    "id": "pds-en#p0032",
    "rank": 32
   },
   {
    "id": "midday-meal-en#p0012",
    "rank": 33
   },
   {
    "id": "awas-yojana-en#p0006",
    "rank": 34
   },
   {
    "id": "mudra-en#p0003",
    "rank": 35
   },
   {
    "id": "jeevan-jyoti-en#p0001",
    "rank": 36
   },
   {
    "id": "jan-dhan-en#p0006",
    "rank": 37
   },
   {
    "id": "awas-yojana-en#p0007",
    "rank": 38
   },
   {
    "id": "swachh-bharat-en#p0028",
    "rank": 39
   },
   {
    "id": "smart-cities-en#p0005",
    "rank": 40
   },
   {
    "id": "jeevan-jyoti-en#p0004",
    "rank": 41
   },
   {
    "id": "smart-cities-en#p0003",
    "rank": 42
   },
   {
    "id": "icds-en#p0001",
    "rank": 43
   },
   {
    "id": "ayushman-bharat-en#p0010",
    "rank": 44
   },
   {
    "id": "mgnrega-en#p0015",
    "rank": 45
   },
   {
    "id": "aadhaar-en#p0005",
    "rank": 46
   },
   {
    "id": "mudra-en#p0014",
    "rank": 47
   },
   {
    "id": "mudra-en#p0009",
    "rank": 48
   },
   {
    "id": "nps-en#p0001",
    "rank": 49
   },
   {
    "id": "smart-cities-en#p0000",
    "rank": 50
   }
  ],
  "dense": [
   {
    "id": "make-in-india-hi#p0009",
    "rank": 1
   },
   {
    "id": "make-in-india-en#p0003",
    "rank": 2
   },
   {
    "id": "swachh-bharat-en#p0019",
    "rank": 3
   },
   {
    "id": "smart-cities-en#p0002",
    "rank": 4
   },
   {
    "id": "make-in-india-en#p0002",
    "rank": 5
   },
   {
    "id": "mudra-en#p0004",
    "rank": 6
   },
   {
    "id": "smart-cities-en#p0000",
    "rank": 7
   },
   {
    "id": "mgnrega-en#p0019",
    "rank": 8
   },
   {
    "id": "mgnrega-en#p0002",
    "rank": 9
   },
   {
    "id": "swachh-bharat-en#p0020",
    "rank": 10
   },
   {
    "id": "mudra-en#p0046",
    "rank": 11
   },
   {
    "id": "swachh-bharat-hi#p0005",
    "rank": 12
   },
   {
    "id": "icds-en#p0003",
    "rank": 13
   },
   {
    "id": "swachh-bharat-en#p0018",
    "rank": 14
   },
   {
    "id": "swachh-bharat-en#p0011",
    "rank": 15
   },
   {
    "id": "smart-cities-en#p0003",
    "rank": 16
   },
   {
    "id": "smart-cities-en#p0004",
    "rank": 17
   },
   {
    "id": "awas-yojana-en#p0006",
    "rank": 18
   },
   {
    "id": "swachh-bharat-en#p0007",
    "rank": 19
   },
   {
    "id": "swachh-bharat-en#p0009",
    "rank": 20
   },
   {
    "id": "make-in-india-en#p0004",
    "rank": 21
   },
   {
    "id": "mudra-en#p0030",
    "rank": 22
   },
   {
    "id": "mudra-en#p0031",
    "rank": 23
   },
   {
    "id": "swachh-bharat-en#p0028",
    "rank": 24
   },
   {
    "id": "swachh-bharat-en#p0004",
    "rank": 25
   },
   {
    "id": "mudra-en#p0005",
    "rank": 26
   },
   {
    "id": "mgnrega-en#p0015",
    "rank": 27
   },
   {
    "id": "smart-cities-en#p0001",
    "rank": 28
   },
   {
    "id": "mudra-en#p0045",
    "rank": 29
   },
   {
    "id": "swachh-bharat-en#p0027",
    "rank": 30
   },
   {
    "id": "skill-india-en#p0002",
    "rank": 31
   },
   {
    "id": "mgnrega-en#p0014",
    "rank": 32
   },
   {
    "id": "awas-yojana-en#p0008",
    "rank": 33
   },
   {
    "id": "aadhaar-en#p0019",
    "rank": 34
   },
   {
    "id": "skill-india-en#p0003",
    "rank": 35
   },
   {
    "id": "make-in-india-en#p0001",
    "rank": 36
   },
   {
    "id": "pds-en#p0012",
    "rank": 37
   },
   {
    "id": "nsap-en#p0007",
    "rank": 38
   },
   {
    "id": "beti-bachao-en#p0001",
    "rank": 39
   },
   {
    "id": "swachh-bharat-en#p0003",
    "rank": 40
   },
   {
    "id": "swachh-bharat-en#p0002",
    "rank": 41
   },
   {
    "id": "mgnrega-en#p0024",
    "rank": 42
   },
   {
    "id": "digital-india-en#p0003",
    "rank": 43
   },
   {
    "id": "awas-yojana-en#p0009",
    "rank": 44
   },
   {
    "id": "make-in-india-hi#p0005",
    "rank": 45
   },
   {
    "id": "make-in-india-en#p0013",
    "rank": 46
   },
   {
    "id": "make-in-india-hi#p0016",
    "rank": 47
   },
   {
    "id": "make-in-india-en#p0005",
    "rank": 48
   },
   {
    "id": "mudra-en#p0042",
    "rank": 49
   },
   {
    "id": "atmanirbhar-en#p0000",
    "rank": 50
   }
  ],
  "passages": {
   "aadhaar-en#p0005": {
    "scheme": "aadhaar",
    "lang": "en",
    "script": "latin",
    "snippet": "The Unique Identification Authority of India (UIDAI) was established on 28 January 2009 through a…"
   },
   "aadhaar-en#p0019": {
    "scheme": "aadhaar",
    "lang": "en",
    "script": "latin",
    "snippet": "In October 2010 R. Ramakumar, an economist at the Tata Institute of Social Sciences, wrote in an editorial…"
   },
   "aadhaar-en#p0034": {
    "scheme": "aadhaar",
    "lang": "en",
    "script": "latin",
    "snippet": "Aadhaar data is linked to the fingerprints of cardholders. This has been used by fraudsters to withdraw money…"
   },
   "aadhaar-en#p0036": {
    "scheme": "aadhaar",
    "lang": "en",
    "script": "latin",
    "snippet": "Many private and public benefits are being linked to Aadhaar numbers and made contingent on it: food aid,…"
   },
   "aadhaar-en#p0040": {
    "scheme": "aadhaar",
    "lang": "en",
    "script": "latin",
    "snippet": "In February 2017, the Unique Identification Authority of India filed a police complaint after confirming that…"
   },
   "aadhaar-en#p0044": {
    "scheme": "aadhaar",
    "lang": "en",
    "script": "latin",
    "snippet": "In 2018, the Aadhaar database suffered several breaches, resulting in 1.1 billion people's data being leaked…"
   },
   "atmanirbhar-en#p0000": {
    "scheme": "atmanirbhar",
    "lang": "en",
    "script": "latin",
    "snippet": "Atmanirbhar Bharat (Hindi: आत्मनिर्भर भारत, \"Self-Reliant India\") is a policy framework and slogan associated…"
   },
   "awas-yojana-en#p0006": {
    "scheme": "awas-yojana",
    "lang": "en",
    "script": "latin",
    "snippet": "As of 25 April 2016, the government has identified 2,508 cities and towns in 26 states for beginning…"
   },
   "awas-yojana-en#p0007": {
    "scheme": "awas-yojana",
    "lang": "en",
    "script": "latin",
    "snippet": "Feb 2018) Maharashtra, 12,123 houses in 13 cities and towns with an investment of ₹868 crore (c. Feb 2018)…"
   },
   "awas-yojana-en#p0008": {
    "scheme": "awas-yojana",
    "lang": "en",
    "script": "latin",
    "snippet": "ICICI Bank is giving subsidized home loans to the people eligible for this scheme. \"Rajiv Awas Yojana (RAY)\"…"
   },
   "awas-yojana-en#p0009": {
    "scheme": "awas-yojana",
    "lang": "en",
    "script": "latin",
    "snippet": "One million beneficiaries were proposed to be covered under Rajiv Awas Yojana. Site selection was to be made…"
   },
   "ayushman-bharat-en#p0010": {
    "scheme": "ayushman-bharat",
    "lang": "en",
    "script": "latin",
    "snippet": "When Ayushman Bharat Yojana (Ayushman Card) began there were questions of how to reconcile its plans with…"
   },
   "beti-bachao-en#p0001": {
    "scheme": "beti-bachao",
    "lang": "en",
    "script": "latin",
    "snippet": "The child sex ratio in India had been going down at an alarming rate. In the population census of 2011, the…"
   },
   "digital-india-en#p0003": {
    "scheme": "digital-india",
    "lang": "en",
    "script": "latin",
    "snippet": "A decade after its launch, assessments have noted that Digital India helped build one of the world's largest…"
   },
   "garib-kalyan-anna-en#p0011": {
    "scheme": "garib-kalyan-anna",
    "lang": "en",
    "script": "latin",
    "snippet": "The schemes extend to 57% of the population (813.5 million out of approximately 1.43 billion in 2024). More…"
   },
   "icds-en#p0001": {
    "scheme": "icds",
    "lang": "en",
    "script": "latin",
    "snippet": "The infant mortality rate of Indian children is 3.4% and the under-five mortality rate is 3.9% and 25% of…"
   },
   "icds-en#p0003": {
    "scheme": "icds",
    "lang": "en",
    "script": "latin",
    "snippet": "By end of 2010, the programme is claiming to reach 80.6 lakh expectant and lactating mothers along with 3.93…"
   },
   "jan-dhan-en#p0000": {
    "scheme": "jan-dhan",
    "lang": "en",
    "script": "latin",
    "snippet": "Pradhan Mantri Jan Dhan Yojana (transl. Prime Minister's Public Finance Scheme) is a financial inclusion…"
   },
   "jan-dhan-en#p0002": {
    "scheme": "jan-dhan",
    "lang": "en",
    "script": "latin",
    "snippet": "Due to the preparations done in the run-up to the inauguration, 15 million bank accounts were opened on…"
   },
   "jan-dhan-en#p0004": {
    "scheme": "jan-dhan",
    "lang": "en",
    "script": "latin",
    "snippet": "As of January 27, 2021, a total number of 417.5 million accounts have been opened under the Pradhan Mantri…"
   },
   "jan-dhan-en#p0005": {
    "scheme": "jan-dhan",
    "lang": "en",
    "script": "latin",
    "snippet": "The scheme has been criticized by the opposition, and that it has created unnecessary work-burden on the…"
   },
   "jan-dhan-en#p0006": {
    "scheme": "jan-dhan",
    "lang": "en",
    "script": "latin",
    "snippet": "In March 2018, the Government of India stated that around 20% of Jan Dhan accounts were lying dormant. In…"
   },
   "jeevan-jyoti-en#p0001": {
    "scheme": "jeevan-jyoti",
    "lang": "en",
    "script": "latin",
    "snippet": "Those who register for auto debit facility will have auto renewal up to 55 years. However, a person over age…"
   },
   "jeevan-jyoti-en#p0004": {
    "scheme": "jeevan-jyoti",
    "lang": "en",
    "script": "latin",
    "snippet": "Over 23.6 crore, 51 crore and 7.6 crore enrolments have been done under PMJJBY, PMSBY & APY respectively till…"
   },
   "kgbv-en#p0002": {
    "scheme": "kgbv",
    "lang": "en",
    "script": "latin",
    "snippet": "The scheme was applicable since its inception in 2004, in Educationally Backward Blocks (EBBs) where the…"
   },
   "make-in-india-en#p0001": {
    "scheme": "make-in-india",
    "lang": "en",
    "script": "latin",
    "snippet": "Announced in 2014, \"Make in India\" had three stated objectives: to increase the manufacturing sector's growth…"
   },
   "make-in-india-en#p0002": {
    "scheme": "make-in-india",
    "lang": "en",
    "script": "latin",
    "snippet": "Following the launch, India received investment commitments worth ₹16.40 lakh crore (US$170 billion) and…"
   },
   "make-in-india-en#p0003": {
    "scheme": "make-in-india",
    "lang": "en",
    "script": "latin",
    "snippet": "The World Bank's 2019 ease of doing business index acknowledged India's jump of 23 positions from its rank of…"
   },
   "make-in-india-en#p0004": {
    "scheme": "make-in-india",
    "lang": "en",
    "script": "latin",
    "snippet": "The campaign was designed by Wieden+Kennedy, with the launch of a web portal and the release of brochures on…"
   },
   "make-in-india-en#p0005": {
    "scheme": "make-in-india",
    "lang": "en",
    "script": "latin",
    "snippet": "As part of the initiative, the government permitted 100% Foreign Direct Investment (FDI) in most sectors in…"
   },
   "make-in-india-en#p0013": {
    "scheme": "make-in-india",
    "lang": "en",
    "script": "latin",
    "snippet": "Motorola Mobility: manufacturing at Sriperumbudur near Chennai run by Flextronics. Micromax: 3 new…"
   },
   "make-in-india-hi#p0005": {
    "scheme": "make-in-india",
    "lang": "hi",
    "script": "deva",
    "snippet": "प्रधानमंत्री नरेंद्र मोदी ने विज्ञान भवन में आयोजित एक समारोह में 25 सितंबर, 2014 को शुरू की \"भारत में बनाओ।\"…"
   },
   "make-in-india-hi#p0009": {
    "scheme": "make-in-india",
    "lang": "hi",
    "script": "deva",
    "snippet": "भारत, व्यापार सूचकांक जून 2014 और जून 2015 में भारत से इस अवधि को कवर करने के लिए विश्व बैंक के 2016 आराम में…"
   },
   "make-in-india-hi#p0016": {
    "scheme": "make-in-india",
    "lang": "hi",
    "script": "deva",
    "snippet": "\" make in India week\" घटना 13 से मुंबई में बांद्रा- कुर्ला कॉम्प्लेक्स फ़रवरी 2016 सप्ताह तक बहु -क्षेत्रीय…"
   },
   "mgnrega-en#p0002": {
    "scheme": "mgnrega",
    "lang": "en",
    "script": "latin",
    "snippet": "Narasimha Rao. It was finally accepted in the parliament and commenced implementation in 625 districts of…"
   },
   "mgnrega-en#p0014": {
    "scheme": "mgnrega",
    "lang": "en",
    "script": "latin",
    "snippet": "This highlights that NREGA may be an effective insurance scheme. A particular focus has been to understand…"
   },
   "mgnrega-en#p0015": {
    "scheme": "mgnrega",
    "lang": "en",
    "script": "latin",
    "snippet": "A study conducted by researchers at the Indian Institute of Science and other collaborators found that…"
   },
   "mgnrega-en#p0019": {
    "scheme": "mgnrega",
    "lang": "en",
    "script": "latin",
    "snippet": "The Prime Minister of India Manmohan Singh released an anthology of research studies on the MGNREGA called…"
   },
   "mgnrega-en#p0024": {
    "scheme": "mgnrega",
    "lang": "en",
    "script": "latin",
    "snippet": "The direct public debate involving the beneficiaries, political representatives, civil servants and, above…"
   },
   "midday-meal-en#p0012": {
    "scheme": "midday-meal",
    "lang": "en",
    "script": "latin",
    "snippet": "International voluntary and charity organisations have assisted. Church World Service has provided milk…"
   },
   "midday-meal-en#p0017": {
    "scheme": "midday-meal",
    "lang": "en",
    "script": "latin",
    "snippet": "Despite the success of the programme, child hunger as a problem persists in India. According to current…"
   },
   "midday-meal-en#p0018": {
    "scheme": "midday-meal",
    "lang": "en",
    "script": "latin",
    "snippet": "The report states that \"improving child nutrition is of utmost urgency in most Indian states\". As the MDM…"
   },
   "mudra-en#p0003": {
    "scheme": "mudra",
    "lang": "en",
    "script": "latin",
    "snippet": "Modi's labour reforms received support from institutions such as the World Bank, but opposition from…"
   },
   "mudra-en#p0004": {
    "scheme": "mudra",
    "lang": "en",
    "script": "latin",
    "snippet": "The government has increased the Budget for National Mission for Green India from Rs. 290…"
   },
   "mudra-en#p0005": {
    "scheme": "mudra",
    "lang": "en",
    "script": "latin",
    "snippet": "The \"Smart Cities\" program is expected to bring IT companies an extra benefit of ₹20 billion (US$210…"
   },
   "mudra-en#p0009": {
    "scheme": "mudra",
    "lang": "en",
    "script": "latin",
    "snippet": "The government of Haryana made changes to its education policy that introduced Hindu religious elements into…"
   },
   "mudra-en#p0014": {
    "scheme": "mudra",
    "lang": "en",
    "script": "latin",
    "snippet": "In the past decade, India has seen a decline in many global freedom indices. In 2020, India reported drop in…"
   },
   "mudra-en#p0030": {
    "scheme": "mudra",
    "lang": "en",
    "script": "latin",
    "snippet": "The Modi administration tried to attract foreign investment in the Indian economy from several sources,…"
   },
   "mudra-en#p0031": {
    "scheme": "mudra",
    "lang": "en",
    "script": "latin",
    "snippet": "During the first few months after the election, Modi made trips to a number of different countries to further…"
   },
   "mudra-en#p0042": {
    "scheme": "mudra",
    "lang": "en",
    "script": "latin",
    "snippet": "The changes were made with the aim of accelerating approval for industrial projects. Other changes included…"
   },
   "mudra-en#p0045": {
    "scheme": "mudra",
    "lang": "en",
    "script": "latin",
    "snippet": "The stated reason was that his conduct in the 2G spectrum allocation case had been suspect: commentators…"
   },
   "mudra-en#p0046": {
    "scheme": "mudra",
    "lang": "en",
    "script": "latin",
    "snippet": "The planning commission had received heavy criticism in previous years for creating inefficiency in the…"
   },
   "mudra-en#p0049": {
    "scheme": "mudra",
    "lang": "en",
    "script": "latin",
    "snippet": "During the second wave of the pandemic in April 2021, Modi's government launched a new policy for vaccines…"
   },
   "nps-en#p0001": {
    "scheme": "nps",
    "lang": "en",
    "script": "latin",
    "snippet": "custodian, Pension Funds, Trustee Bank, Central Recordkeeping Agency, Point of Presence, Aggregators, and of…"
   },
   "nsap-en#p0007": {
    "scheme": "nsap",
    "lang": "en",
    "script": "latin",
    "snippet": "Recent studies of NSAP show that the social pension schemes are performing 'reasonably well' and 'levels of…"
   },
   "pds-en#p0012": {
    "scheme": "pds",
    "lang": "en",
    "script": "latin",
    "snippet": "While this improvement was modest, it showed that improvements in PDS functioning was certainly possible. The…"
   },
   "pds-en#p0028": {
    "scheme": "pds",
    "lang": "en",
    "script": "latin",
    "snippet": "Moreover, there are no reliable estimates of the size of identity and quantity fraud in recent years at the…"
   },
   "pds-en#p0032": {
    "scheme": "pds",
    "lang": "en",
    "script": "latin",
    "snippet": "A public distribution shop, also known as fair price shop (FPS), is a part of India's public system…"
   },
   "pm-kisan-en#p0001": {
    "scheme": "pm-kisan",
    "lang": "en",
    "script": "latin",
    "snippet": "The scheme was first conceived and implemented by Government of Telangana as the Rythu Bandhu scheme, where a…"
   },
   "rte-act-en#p0003": {
    "scheme": "rte-act",
    "lang": "en",
    "script": "latin",
    "snippet": "C. Chagla, 1964 During the 1990s, with support from the World Bank, efforts were made to establish schools…"
   },
   "rte-act-en#p0006": {
    "scheme": "rte-act",
    "lang": "en",
    "script": "latin",
    "snippet": "The Act mandates regular surveys to identify children in need of education and to ensure that suitable…"
   },
   "skill-india-en#p0002": {
    "scheme": "skill-india",
    "lang": "en",
    "script": "latin",
    "snippet": "16 April 2022: India's first Skill India International Centre will be set up in Bhubaneswar for training…"
   },
   "skill-india-en#p0003": {
    "scheme": "skill-india",
    "lang": "en",
    "script": "latin",
    "snippet": "Oracle on 12 February 2016 announced that it will build a new 2.8 million sq. ft. campus in Bengaluru, which…"
   },
   "smart-cities-en#p0000": {
    "scheme": "smart-cities",
    "lang": "en",
    "script": "latin",
    "snippet": "Smart Cities Mission is an urban renewal and retrofitting program by the Government of India with the mission…"
   },
   "smart-cities-en#p0001": {
    "scheme": "smart-cities",
    "lang": "en",
    "script": "latin",
    "snippet": "Smart Cities Mission envisions developing areas within selected cities in the country as model areas based on…"
   },
   "smart-cities-en#p0002": {
    "scheme": "smart-cities",
    "lang": "en",
    "script": "latin",
    "snippet": "The mission was launched by Prime Minister Narendra Modi on 25 June 2015. In the 2015 Union budget of India,…"
   },
   "smart-cities-en#p0003": {
    "scheme": "smart-cities",
    "lang": "en",
    "script": "latin",
    "snippet": "On 28 January 2016, a batch of 20 cities known as \"lighthouse cities\" were selected in the first round of the…"
   },
   "smart-cities-en#p0004": {
    "scheme": "smart-cities",
    "lang": "en",
    "script": "latin",
    "snippet": "The programme has faced delays in the selection of cities, and in the execution of the projects. Originally…"
   },
   "smart-cities-en#p0005": {
    "scheme": "smart-cities",
    "lang": "en",
    "script": "latin",
    "snippet": "The CAG report cited deficient financial administration, including the inclusion of unfeasible projects,…"
   },
   "swachh-bharat-en#p0002": {
    "scheme": "swachh-bharat",
    "lang": "en",
    "script": "latin",
    "snippet": "The campaign's official name is in Hindi. In English, it translates to \"Clean India Mission\". The campaign…"
   },
   "swachh-bharat-en#p0003": {
    "scheme": "swachh-bharat",
    "lang": "en",
    "script": "latin",
    "snippet": "The rural division has a five-tier mechanism: central, state, district, block panchayat, and gram panchayat.…"
   },
   "swachh-bharat-en#p0004": {
    "scheme": "swachh-bharat",
    "lang": "en",
    "script": "latin",
    "snippet": "This figure included 17% of the rural population (about 154 million) and 0.5% of the urban population…"
   },
   "swachh-bharat-en#p0007": {
    "scheme": "swachh-bharat",
    "lang": "en",
    "script": "latin",
    "snippet": "The TSC focused on increasing awareness around rural sanitation and informed rural populations about…"
   },
   "swachh-bharat-en#p0009": {
    "scheme": "swachh-bharat",
    "lang": "en",
    "script": "latin",
    "snippet": "36 states and union territories, 706 districts and over 603,175 villages have been declared open…"
   },
   "swachh-bharat-en#p0011": {
    "scheme": "swachh-bharat",
    "lang": "en",
    "script": "latin",
    "snippet": "In the Kabirdham district of Chhattisgarh, around 1.38 lakh children belonging to 1700 schools wrote to their…"
   },
   "swachh-bharat-en#p0018": {
    "scheme": "swachh-bharat",
    "lang": "en",
    "script": "latin",
    "snippet": "Swachh Survekshan, commissioned by Ministry of Urban Development and carried out by Quality Council of India,…"
   },
   "swachh-bharat-en#p0019": {
    "scheme": "swachh-bharat",
    "lang": "en",
    "script": "latin",
    "snippet": "According to the dashboards maintained by respective ministries, more than 100 million individual…"
   },
   "swachh-bharat-en#p0020": {
    "scheme": "swachh-bharat",
    "lang": "en",
    "script": "latin",
    "snippet": "The World Bank reports that 96% of Indians who have a toilet use it. The World Health Organization (WHO) has…"
   },
   "swachh-bharat-en#p0022": {
    "scheme": "swachh-bharat",
    "lang": "en",
    "script": "latin",
    "snippet": "The mission is noted as the world's largest sanitation program. It claimed to have provided millions of…"
   },
   "swachh-bharat-en#p0027": {
    "scheme": "swachh-bharat",
    "lang": "en",
    "script": "latin",
    "snippet": "By adding millions of on-site sanitation systems and not considering fecal sludge management, it will further…"
   },
   "swachh-bharat-en#p0028": {
    "scheme": "swachh-bharat",
    "lang": "en",
    "script": "latin",
    "snippet": "A report by WSSCC in 2019 found that the impact of the SBM for the most vulnerable was limited. The report…"
   },
   "swachh-bharat-hi#p0005": {
    "scheme": "swachh-bharat",
    "lang": "hi",
    "script": "deva",
    "snippet": "भारत सरकार ने 15 फरवरी 2016 को सफाई रैंकिंग जारी की। सफाई सेलेक्शन -2016 में 73 शहरों को सफाई और स्वच्छता के…"
   }
  }
 },
 "taxonomy": [
  {
   "class": "out-of-scope",
   "question": "When will the CBSE Class 12 board exam results be announced this year?",
   "id": "un-out-of-scope-101"
  },
  {
   "class": "near-miss",
   "question": "सार्वजनिक वितरण प्रणाली के लिए वर्ष 2025-26 का बजट कितना है?",
   "id": "un-near-miss-007"
  },
  {
   "class": "false-premise",
   "question": "How much laptop allowance does National Health Mission provide?",
   "id": "un-false-premise-012"
  },
  {
   "class": "under-specified",
   "question": "When was the scheme launched?",
   "id": "un-under-specified-009"
  }
 ],
 "langid": {
  "unambiguous": [
   "aapka",
   "aapki",
   "agar",
   "apna",
   "apne",
   "apni",
   "aur",
   "batao",
   "bataye",
   "bhi",
   "chahiye",
   "dena",
   "deta",
   "diya",
   "hai",
   "haii",
   "hain",
   "hoga",
   "hogi",
   "hona",
   "honge",
   "hota",
   "hote",
   "hoti",
   "iska",
   "iski",
   "jab",
   "jarurat",
   "jaruri",
   "jis",
   "ka",
   "kab",
   "kahaan",
   "kahan",
   "kaisa",
   "kaise",
   "kaisi",
   "kare",
   "karna",
   "karne",
   "karta",
   "karti",
   "kaun",
   "kaunsa",
   "kaunse",
   "ke",
   "ki",
   "kisi",
   "kisne",
   "kitna",
   "kitnaa",
   "kitne",
   "kitni",
   "ko",
   "koi",
   "kuch",
   "kya",
   "kyaa",
   "kyon",
   "kyu",
   "kyun",
   "lekin",
   "liye",
   "magar",
   "mai",
   "mein",
   "mera",
   "mere",
   "meri",
   "milega",
   "milne",
   "milta",
   "milti",
   "nahi",
   "nahin",
   "pe",
   "sab",
   "sabhi",
   "sakta",
   "sakte",
   "sakti",
   "se",
   "tak",
   "tera",
   "teri",
   "tha",
   "thi",
   "uska",
   "uski",
   "wala",
   "wale",
   "wali",
   "woh",
   "yadi",
   "yeh",
   "zarurat",
   "zaruri"
  ],
  "indic_floor": 0.6
 }
};
