// Generated by scripts/build-web.py from docs/demo/*.json. Do not edit.
window.INDICRAG_DEMO = [
 {
  "query": "How much is the annual premium of Pradhan Mantri Suraksha Bima Yojana?",
  "query_type": "English",
  "answerability": "ANSWERABLE",
  "answer": "Pradhan Mantri Suraksha Bima Yojana is available to people (Indian Resident or NRI) between 18 and 70 years of age with bank accounts.",
  "confidence": 0.95,
  "query_lang": "en",
  "answer_lang": "en",
  "citations": [
   {
    "passage_id": "suraksha-bima-en#p0001",
    "doc_id": "suraksha-bima-en",
    "scheme": "suraksha-bima",
    "lang": "en",
    "section_path": "Provisions",
    "score": 0.0328,
    "snippet": "Pradhan Mantri Suraksha Bima Yojana is available to people (Indian Resident or NRI) between 18 and 70 years of age with bank accounts. It has an annual premium of ₹20 (21¢ US). Goods and Services Tax (GST) is exempted on Pradhan Mantri Suraksha Bima Yojana. The amount is automatically debited from t"
   },
   {
    "passage_id": "jeevan-jyoti-en#p0000",
    "doc_id": "jeevan-jyoti-en",
    "scheme": "jeevan-jyoti",
    "lang": "en",
    "section_path": "Introduction",
    "score": 0.0318,
    "snippet": "Pradhan Mantri Jeevan Jyoti Bima Yojana (Prime Minister Jeevan Jyoti Insurance Scheme) is a Government-backed life insurance scheme in India. It was originally mentioned in the year 2015 budget speech by the then-Finance Minister, Arun Jaitley in February 2015. It was formally launched by Prime Mini"
   },
   {
    "passage_id": "suraksha-bima-en#p0003",
    "doc_id": "suraksha-bima-en",
    "scheme": "suraksha-bima",
    "lang": "en",
    "section_path": "Criticism",
    "score": 0.0318,
    "snippet": "The success rate of the Pradhan Mantri Suraksha Bima Yojana (PMSBY) can be viewed through its high enrollment figures (over 50 crore cumulative enrollments as of May 2025), extensive reach into rural areas, and low rejection rate; however, it has experienced challenges in timely claim settlement, wi"
   },
   {
    "passage_id": "suraksha-bima-en#p0000",
    "doc_id": "suraksha-bima-en",
    "scheme": "suraksha-bima",
    "lang": "en",
    "section_path": "Introduction",
    "score": 0.0317,
    "snippet": "Pradhan Mantri Suraksha Bima Yojana (PMSBY, translation: Prime Minister's Safety Insurance Scheme) is a government-backed accident insurance scheme in India. It was originally mentioned in the 2015 budget speech by Finance Minister Arun Jaitley in February 2015. It was formally launched by the Prime"
   },
   {
    "passage_id": "jeevan-jyoti-en#p0001",
    "doc_id": "jeevan-jyoti-en",
    "scheme": "jeevan-jyoti",
    "lang": "en",
    "section_path": "Introduction",
    "score": 0.0305,
    "snippet": "Those who register for auto debit facility will have auto renewal up to 55 years. However, a person over age 50 cannot register to this scheme. There is no need for a person to submit health report or certificate while joining to this scheme. In case of death due to any cause, the payment to the nom"
   }
  ],
  "explanation": "Extracted verbatim from suraksha-bima-en#p0001 (suraksha-bima, Provisions).",
  "retrieval": {
   "method": "hybrid",
   "k": 5,
   "top_score": 0.0328,
   "margin": 0.001,
   "n_candidates": 5,
   "bm25_top": 30.5053,
   "bm25_floor": 18.08
  },
  "model": "extractive",
  "prompt_hash": ""
 },
 {
  "query": "मनरेगा के तहत कितने दिन का रोजगार मिलता है?",
  "query_type": "Indic",
  "answerability": "ANSWERABLE",
  "answer": "2008-09 के दौरान 4,49,40,870 ग्रामीण परिवारों को मनरेगा के तहत रोजगार उपलब्ध कराया गया, जहां प्रत्येक परिवार में 48 कार्य दिवस का राष्ट्रीय औसत था।",
  "confidence": 0.7445,
  "query_lang": "hi",
  "answer_lang": "hi",
  "citations": [
   {
    "passage_id": "mgnrega-hi#p0004",
    "doc_id": "mgnrega-hi",
    "scheme": "mgnrega",
    "lang": "hi",
    "section_path": "क्रियान्वयन",
    "score": 0.0325,
    "snippet": "भारत का नियंत्रक एवं महालेखा परीक्षक (सीएजी) ने मनरेगा के कार्यान्वयन के प्रदर्शन लेखापरीक्षा में इस अधिनियम के कार्यान्वयन में \"बड़ी कमियों\" को पाया है। इस योजना को फरवरी 2006 में 200 जिलों में शुरू किया गया था और अंत में 593 जिलों तक विस्तारित किया गया। 2008-09 के दौरान 4,49,40,870 ग्रामीण परिवारो"
   },
   {
    "passage_id": "mgnrega-hi#p0002",
    "doc_id": "mgnrega-hi",
    "scheme": "mgnrega",
    "lang": "hi",
    "section_path": "योजना",
    "score": 0.0323,
    "snippet": "यह अधिनियम, राज्य सरकारों को \"मनरेगा योजनाओं\" को लागू करने के निर्देश देता है। मनरेगा के तहत, केन्द्र सरकार मजदूरी की लागत, माल की लागत का 3/4 और प्रशासनिक लागत का कुछ प्रतिशत वहन करती है। राज्य सरकारें बेरोजगारी भत्ता, माल की लागत का 1/4 और राज्य परिषद की प्रशासनिक लागत को वहन करती है। चूंकि राज्य "
   },
   {
    "passage_id": "mgnrega-hi#p0000",
    "doc_id": "mgnrega-hi",
    "scheme": "mgnrega",
    "lang": "hi",
    "section_path": "Introduction",
    "score": 0.032,
    "snippet": "महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी अधिनियम (मनरेगा / MNREGA) भारत में लागू एक रोजगार गारंटी योजना है, जिसे 5 सितम्बर 2005 को विधान द्वारा अधिनियमित किया गया। यह योजना प्रत्येक वित्तीय वर्ष में किसी भी ग्रामीण परिवार के उन वयस्क सदस्यों को 100 दिन का रोजगार उपलब्ध कराती है जो प्रतिदिन 220 "
   },
   {
    "passage_id": "mgnrega-hi#p0005",
    "doc_id": "mgnrega-hi",
    "scheme": "mgnrega",
    "lang": "hi",
    "section_path": "कार्य/गतिविधियां",
    "score": 0.031,
    "snippet": "मनरेगा ग्रामीण विकास और रोजगार के दोहरे लक्ष्य को प्राप्त करता है। मनरेगा यह उल्लेख करता है कि कार्य को ग्रामीण विकास गतिविधियों के एक विशिष्ट सेट की ओर उन्मुख होना चाहिए जैसे: जल संरक्षण और संचयन, वनीकरण, ग्रामीण संपर्क-तंत्र, बाढ़ नियंत्रण और सुरक्षा जिसमें शामिल है तटबंधों का निर्माण और मरम्मत, आ"
   },
   {
    "passage_id": "mgnrega-en#p0001",
    "doc_id": "mgnrega-en",
    "scheme": "mgnrega",
    "lang": "en",
    "section_path": "Introduction",
    "score": 0.0303,
    "snippet": "It aimed to enhance livelihood security in rural areas by providing at least 100 days of assured and guaranteed wage employment in a financial year to at least one member of every Indian rural household whose adult members volunteer to do unskilled manual work. Women are guaranteed one half of the j"
   }
  ],
  "explanation": "Extracted verbatim from mgnrega-hi#p0004 (mgnrega, क्रियान्वयन).",
  "retrieval": {
   "method": "hybrid",
   "k": 5,
   "top_score": 0.0325,
   "margin": 0.0003,
   "n_candidates": 5,
   "bm25_top": 19.3204,
   "bm25_floor": 18.08
  },
  "model": "extractive",
  "prompt_hash": ""
 },
 {
  "query": "Scholarship ke liye minimum eligibility kya hai?",
  "query_type": "Code-Mixed",
  "answerability": "UNANSWERABLE",
  "answer": "Insufficient information available in the provided documents.",
  "confidence": 0.9677,
  "query_lang": "hi-en",
  "answer_lang": "",
  "citations": [
   {
    "passage_id": "awas-yojana-hi#p0003",
    "doc_id": "awas-yojana-hi",
    "scheme": "awas-yojana",
    "lang": "hi",
    "section_path": "योजना > पात्रता",
    "score": 0.0323,
    "snippet": "इस योजना हेतु भारत सरकार द्वारा निम्न पात्रता मापदंड तय किया गया है:-\n\nआवेदक की उम्र 70 से कम हो, आवेदक या उसके परिवार के किसी सदस्य के नाम से कोई घर या फ्लॅट न हो, आवेदक द्वारा घर खरीदने के लिए किसी भी प्रकार का सरकारी छुट न लिया हो, घर का मालिकाना हक या तो महिला के नाम से हो, या उस परिवार में केवल"
   },
   {
    "passage_id": "sukanya-en#p0003",
    "doc_id": "sukanya-en",
    "scheme": "sukanya",
    "lang": "en",
    "section_path": "Summary",
    "score": 0.0313,
    "snippet": "If the girl is over 18 and married, normal closure is allowed. The Sukanya Samriddhi Yojana (SSY) scheme is highly flexible regarding annual deposit amounts. You are not required to deposit the same amount every year.Key Deposit RulesFlexible Amounts: You can choose to deposit any amount between the"
   },
   {
    "passage_id": "atal-pension-en#p0002",
    "doc_id": "atal-pension-en",
    "scheme": "atal-pension",
    "lang": "en",
    "section_path": "Scheme",
    "score": 0.0307,
    "snippet": "To be eligible to avail the scheme, a person's age should be between 18 and 40 years. The pension of the person joining the scheme depends on the investment made in it and the time limit of investment. In order to incentivize people to enroll in this scheme and widen its reach, the government announ"
   },
   {
    "passage_id": "sukanya-en#p0001",
    "doc_id": "sukanya-en",
    "scheme": "sukanya",
    "lang": "en",
    "section_path": "Summary",
    "score": 0.0288,
    "snippet": "The scheme was launched by Prime Minister Narendra Modi on 22 January 2015 in Panipat, Haryana. The accounts can be opened at any India Post office or a branch of some authorized commercial banks. Initially, the interest rate was set at 9.1% but later revised to 9.2% in late March 2015 for FY2015-16"
   },
   {
    "passage_id": "epfo-en#p0014",
    "doc_id": "epfo-en",
    "scheme": "epfo",
    "lang": "en",
    "section_path": "EPF calculation > Percentage breakdown",
    "score": 0.0281,
    "snippet": "EPFOF dues has two contributions. One is the employee's contribution which is deducted from employee's salary / wages and another is employer's contribution which is to be paid by the employer every month. The employee's contribution is 12% of the basic wage as per sec.2(b) of the act and employer's"
   }
  ],
  "explanation": "",
  "retrieval": {
   "method": "hybrid",
   "k": 5,
   "top_score": 0.0323,
   "margin": 0.001,
   "n_candidates": 5,
   "bm25_top": 10.2878,
   "bm25_floor": 18.08
  },
  "model": "",
  "prompt_hash": ""
 },
 {
  "query": "सुकन्या समृद्धि खाता कितने वर्ष में परिपक्व होता है?",
  "query_type": "Indic",
  "answerability": "ANSWERABLE",
  "answer": "सुकन्या समृद्धि में केवल जन्म से लेकर 10 वर्ष की उम्र की लड़की के नाम पर ही खाता खुलवाया जा सकता है | अर्थात सुकन्या समृद्धि के अंतर्गत 10 वर्ष से अधिक उम्र की लड़कियों का अकाउंट ओपन नहीं किया जा सकता है | इस योजना का लाभ हिंदू अविभाजित परिवार (HUF) एवं अनिवासी भारतीय (एन आर आई) नहीं प्राप्त कर सकते हैं | यदि खाता ओपन करने के पश्चात कोई बच्ची एन आर आई बन जाती है | तो उसे सुकन्या समृद्धि योजना का खाता बंद करना होगा | यदि खाता बंद नहीं किया जाता है | तो एन आर आई बनने के पश्चात इस खाते में किसी प्रकार का ब्याज प्रदान नहीं किया जाएगा |",
  "confidence": 0.6898,
  "query_lang": "hi",
  "answer_lang": "hi",
  "citations": [
   {
    "passage_id": "sukanya-hi#p0008",
    "doc_id": "sukanya-hi",
    "scheme": "sukanya",
    "lang": "hi",
    "section_path": "सुकन्‍या समृद्धि योजना में कौन खाता खोल सकता है –",
    "score": 0.0325,
    "snippet": "सुकन्या समृद्धि में केवल जन्म से लेकर 10 वर्ष की उम्र की लड़की के नाम पर ही खाता खुलवाया जा सकता है | अर्थात सुकन्या समृद्धि के अंतर्गत 10 वर्ष से अधिक उम्र की लड़कियों का अकाउंट ओपन नहीं किया जा सकता है | इस योजना का लाभ हिंदू अविभाजित परिवार (HUF) एवं अनिवासी भारतीय (एन आर आई) नहीं प्राप्त कर सकते"
   },
   {
    "passage_id": "sukanya-hi#p0000",
    "doc_id": "sukanya-hi",
    "scheme": "sukanya",
    "lang": "hi",
    "section_path": "Introduction",
    "score": 0.0323,
    "snippet": "सुकन्या समृद्धि भारत की एक छोटी बचत योजना है, जिसकी शुरुआत 'बेटी बचाओ बेटी पढ़ाओ' अभियान के तहत की गयी | जिसके अंतर्गत माता-पिता या कानूनी अभिभावक कन्या के नाम से खाता खोल सकते हैं इस योजना के अंतर्गत खाता खुलवाने के लिए बच्ची की आयु सीमा 10 वर्ष से कम होनी चाहिए । यह खाता किसी भी डाकखाने और निर्धार"
   },
   {
    "passage_id": "sukanya-hi#p0005",
    "doc_id": "sukanya-hi",
    "scheme": "sukanya",
    "lang": "hi",
    "section_path": "विशेषताएँ",
    "score": 0.032,
    "snippet": "इस स्थिति में खाते को प्रति वर्ष 50 रुपये पेनाल्टी के साथ दोबारा चालू किया जा सकता है, लेकिन न्यूनतम रकम भी जमा करनी होगी। 21 वर्ष की परिपक्वता अवधि पूरी होने के पहले खाताधारी लड़की रकम निकाल सकती है बशर्ते कि उसकी आयु 18 वर्ष की हो गई हो। इस स्थिति में वह कुल जमा राशि का 50 प्रतिशत ही निकाल पाएगी। "
   },
   {
    "passage_id": "sukanya-hi#p0004",
    "doc_id": "sukanya-hi",
    "scheme": "sukanya",
    "lang": "hi",
    "section_path": "विशेषताएँ",
    "score": 0.0312,
    "snippet": "खाते की वैधानिकता उसके खोले जाने की तारीख से लेकर 21 वर्ष की है, जिसके बाद रकम परिपक्व होकर उस लड़की को दे दी जाएगी जिसके नाम पर खाता है। यदि परिपक्वता के बाद खाता बंद नहीं किया जाता है तो बैलेंस रकम पर ब्याज मिलता रहेगा, जिसके बारे में समय-समय पर सूचना प्रदान की जाती रहेगी। यदि लड़की का विवाह 21 वर"
   },
   {
    "passage_id": "sukanya-hi#p0007",
    "doc_id": "sukanya-hi",
    "scheme": "sukanya",
    "lang": "hi",
    "section_path": "तुलना",
    "score": 0.0308,
    "snippet": "सार्वजनिक भविष्य निधि (PPF) और सुकन्या समृद्धि योजना (SSY) दोनों भारत सरकार द्वारा समर्थित दीर्घकालिक बचत योजनाएँ हैं। PPF में कोई भी पात्र भारतीय निवेश कर सकता है, जबकि SSY केवल बालिका के नाम पर खोले जाने वाले खाते के लिए उपलब्ध है। SSY में ब्याज दर सामान्यतः PPF की तुलना में अधिक रही है, जबकि दोनो"
   }
  ],
  "explanation": "Extracted verbatim from sukanya-hi#p0008 (sukanya, सुकन्‍या समृद्धि योजना में कौन खाता खोल सकता है –).",
  "retrieval": {
   "method": "hybrid",
   "k": 5,
   "top_score": 0.0325,
   "margin": 0.0003,
   "n_candidates": 5,
   "bm25_top": 26.4754,
   "bm25_floor": 18.08
  },
  "model": "extractive",
  "prompt_hash": ""
 },
 {
  "query": "What is the interest rate on a Kisan Credit Card loan in Nagaland?",
  "query_type": "English",
  "answerability": "ANSWERABLE",
  "answer": "The Kisan Credit Card (KCC) scheme is a credit scheme introduced in August 1998 by Indian public sector banks to issue kisan credit card to the farmers of India.",
  "confidence": 0.6548,
  "query_lang": "en",
  "answer_lang": "en",
  "citations": [
   {
    "passage_id": "kisan-credit-card-en#p0000",
    "doc_id": "kisan-credit-card-en",
    "scheme": "kisan-credit-card",
    "lang": "en",
    "section_path": "Introduction",
    "score": 0.0328,
    "snippet": "The Kisan Credit Card (KCC) scheme is a credit scheme introduced in August 1998 by Indian public sector banks to issue kisan credit card to the farmers of India. This model scheme was prepared by the National Bank for Agriculture and Rural Development (NABARD) on the recommendations of the R. V. Gup"
   },
   {
    "passage_id": "stand-up-india-hi#p0002",
    "doc_id": "stand-up-india-hi",
    "scheme": "stand-up-india",
    "lang": "hi",
    "section_path": "Stand Up India Scheme की मुख्य विशेषताए > स्टैंड उप इंडिया स्कीम का ऋण विवरण (Loan Details)",
    "score": 0.0581,
    "snippet": "ऋण राशि ₹10 लाख से ₹1 करोड़ तक ऋण का प्रकार - Composite Loan(Term Loan+Working capital) ब्याज दर - Marginal Cost of Lending Rate (MCLR) + अधिकतम 3% मार्जिन - अधिकतम 25% (योजना में 15% तक सहायता संभव) भुगतान अवधि - अधिकतम 7 वर्ष छूट अवधि - अधिकतम 18 महीने तक\n\nइस योजना के विषय में विस्तृत जानकारी नीचे"
   },
   {
    "passage_id": "indira-awaas-en#p0007",
    "doc_id": "indira-awaas-en",
    "scheme": "indira-awaas",
    "lang": "en",
    "section_path": "Eligibility > Who is not eligible",
    "score": 0.0318,
    "snippet": "13 parameters set by the government of India exclude households or individuals from this program:\n\nHousehold having three or four wheeler and motorized boat;\nHousehold having mechanized three or four wheeler agriculture or allied equipment;\nKisan credit card holder having limit of 50,000 rupees;\nHou"
   },
   {
    "passage_id": "sukanya-en#p0001",
    "doc_id": "sukanya-en",
    "scheme": "sukanya",
    "lang": "en",
    "section_path": "Summary",
    "score": 0.0303,
    "snippet": "The scheme was launched by Prime Minister Narendra Modi on 22 January 2015 in Panipat, Haryana. The accounts can be opened at any India Post office or a branch of some authorized commercial banks. Initially, the interest rate was set at 9.1% but later revised to 9.2% in late March 2015 for FY2015-16"
   },
   {
    "passage_id": "kisan-credit-card-hi#p0000",
    "doc_id": "kisan-credit-card-hi",
    "scheme": "kisan-credit-card",
    "lang": "hi",
    "section_path": "Introduction",
    "score": 0.0303,
    "snippet": "किसान क्रेडिट कार्ड ( केसीसी ) योजना भारत के किसानों को किसान क्रेडिट कार्ड जारी करने के लिए भारतीय सार्वजनिक क्षेत्र के बैंकों द्वारा अगस्त 1998 में शुरू की गई एक क्रेडिट योजना है। यह मॉडल योजना कृषि आवश्यकताओं के लिए अग्रिम प्रदान करने के लिए आरवी गुप्ता समिति की सिफारिशों पर राष्ट्रीय कृषि और ग्र"
   }
  ],
  "explanation": "Extracted verbatim from kisan-credit-card-en#p0000 (kisan-credit-card, Introduction).",
  "retrieval": {
   "method": "hybrid",
   "k": 5,
   "top_score": 0.0581,
   "margin": 0.0253,
   "n_candidates": 5,
   "bm25_top": 20.7458,
   "bm25_floor": 18.08
  },
  "model": "extractive",
  "prompt_hash": ""
 },
 {
  "query": "PMJDY ke tahat kitne bank khate khole gaye?",
  "query_type": "Code-Mixed",
  "answerability": "UNANSWERABLE",
  "answer": "Insufficient information available in the provided documents.",
  "confidence": 0.9683,
  "query_lang": "hi-en",
  "answer_lang": "",
  "citations": [
   {
    "passage_id": "jan-dhan-hi#p0000",
    "doc_id": "jan-dhan-hi",
    "scheme": "jan-dhan",
    "lang": "hi",
    "section_path": "Introduction",
    "score": 0.0317,
    "snippet": "प्रधानमंत्री जन धन योजना (संक्षेप में - पीएमजेडीवाई) भारत में वित्तीय समावेशन पर राष्ट्रीय मिशन है और जिसका उद्देश्य देश भर में सभी परिवारों को बैंकिंग सुविधाएं मुहैया कराना और हर परिवार का बैंक खाता खोलना है। इस योजना की घोषणा 15 अगस्त 2014 को तथा इसका शुभारंभ 28 अगस्त 2014 को भारतीय प्रधानमंत्री श"
   },
   {
    "passage_id": "jan-dhan-en#p0003",
    "doc_id": "jan-dhan-en",
    "scheme": "jan-dhan",
    "lang": "en",
    "section_path": "Performance",
    "score": 0.0313,
    "snippet": "Uttar Pradesh and West Bengal have 29% of the total deposits under the scheme, whereas Kerala and Goa became the first states in the country to have at least one basic bank account in every household. The total number of account holders stood at 294.8 million, including 176.1 million account holders"
   },
   {
    "passage_id": "pmkvy-hi#p0000",
    "doc_id": "pmkvy-hi",
    "scheme": "pmkvy",
    "lang": "hi",
    "section_path": "Introduction",
    "score": 0.0312,
    "snippet": "प्रधानमंत्री कौशल विकास योजना (PMKVY)। इसे प्रधानमंत्री यूथ ट्रेनिंग प्रोग्राम के नाम से भी जाना जाता है। भारत सरकार ने इस योजना को जुलाई 2015 में शुरू किया गया था। इस योजना के तहत 2020 तक एक करोड़ युवाओं को प्रशिक्षण (ट्रेनिंग) देने की योजना बनाई गई थी। इस योजना का उद्देश्य ऐसे लोगों को रोजगार मुहै"
   },
   {
    "passage_id": "mudra-en#p0006",
    "doc_id": "mudra-en",
    "scheme": "mudra",
    "lang": "en",
    "section_path": "Economic policies > Social welfare",
    "score": 0.0308,
    "snippet": "Modi launched Pradhan Mantri Jan Dhan Yojana (PMJDY) in August 2014. The initiative aimed to create bank accounts and debit cards for 150 million families, and to allow them an overdraft of ₹5,000 (US$52) and accident insurance. After the launch, 125.4 million accounts were opened by January 2015. T"
   },
   {
    "passage_id": "jan-dhan-en#p0004",
    "doc_id": "jan-dhan-en",
    "scheme": "jan-dhan",
    "lang": "en",
    "section_path": "Performance",
    "score": 0.0303,
    "snippet": "As of January 27, 2021, a total number of 417.5 million accounts have been opened under the Pradhan Mantri Jan Dhan Yojana (PMJDY), out of which 359.6 million accounts are operative. According to the World Bank's Spring 2025 Poverty and Equity Brief, approximately 171 million people in India moved o"
   }
  ],
  "explanation": "",
  "retrieval": {
   "method": "hybrid",
   "k": 5,
   "top_score": 0.0317,
   "margin": 0.0005,
   "n_candidates": 5,
   "bm25_top": 10.7209,
   "bm25_floor": 18.08
  },
  "model": "",
  "prompt_hash": ""
 }
];
